// generated by Fast Light User Interface Designer (fluid) version 1.0102

#include <libintl.h>
#include "gui.h"

Fl_Menu_Item menu_[] = {
 {gettext("Edit"), 0,  0, 0, 64, 0, 0, 14, 56},
 {gettext("Copy"), 0x40063,  (Fl_Callback*)cb_copy, 0, 0, 0, 0, 14, 56},
 {gettext("Paste"), 0x40076,  (Fl_Callback*)cb_paste, 0, 0, 0, 0, 14, 56},
 {0},
 {gettext("Display"), 0,  0, 0, 64, 0, 0, 14, 56},
 {gettext("Group numbers"), 0,  (Fl_Callback*)cb_group, 0, 2, 0, 0, 14, 56},
 {0},
 {gettext("?"), 0,  0, 0, 64, 0, 0, 14, 56},
 {gettext("About..."), 0,  (Fl_Callback*)cb_about, 0, 0, 0, 0, 14, 56},
 {0},
 {0}
};

Fl_Box *mem_flag=(Fl_Box *)0;

Fl_Button *display=(Fl_Button *)0;

Fl_Window* make_window() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(225, 205, gettext("fladder"));
    w = o;
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 230, 20);
      o->menu(menu_);
    }
    { Fl_Button* o = new Fl_Button(50, 55, 65, 25, gettext("DEL"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(4);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_clear, (void*)(1));
    }
    { Fl_Button* o = new Fl_Button(120, 55, 50, 25, gettext("CE"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(4);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_clear, (void*)(2));
    }
    { Fl_Button* o = new Fl_Button(50, 85, 30, 25, gettext("7"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(7));
      o->align(FL_ALIGN_TEXT_OVER_IMAGE);
    }
    { Fl_Button* o = new Fl_Button(85, 85, 30, 25, gettext("8"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(8));
    }
    { Fl_Button* o = new Fl_Button(120, 85, 30, 25, gettext("9"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(9));
    }
    { Fl_Button* o = new Fl_Button(155, 85, 30, 25, gettext("/"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(1);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_op, (void*)(1));
    }
    { Fl_Button* o = new Fl_Button(190, 85, 30, 25, gettext("sqrt"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(1);
      o->callback((Fl_Callback*)cb_op, (void*)(2));
      o->labelcolor(3);
    }
    { Fl_Button* o = new Fl_Button(5, 85, 30, 25, gettext("MC"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(4);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_memory, (void*)(1));
    }
    { Fl_Button* o = new Fl_Button(175, 55, 45, 25, gettext("C"));
      o->box(FL_RSHADOW_BOX);
      o->color(4);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_clear, (void*)(3));
    }
    { Fl_Button* o = new Fl_Button(5, 115, 30, 25, gettext("MR"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(4);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_memory, (void*)(2));
    }
    { Fl_Button* o = new Fl_Button(50, 115, 30, 25, gettext("4"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(4));
    }
    { Fl_Button* o = new Fl_Button(85, 115, 30, 25, gettext("5"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(5));
    }
    { Fl_Button* o = new Fl_Button(120, 115, 30, 25, gettext("6"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(6));
    }
    { Fl_Button* o = new Fl_Button(155, 115, 30, 25, gettext("*"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(1);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_op, (void*)(3));
    }
    { Fl_Button* o = new Fl_Button(190, 115, 30, 25, gettext("%"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(1);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_op, (void*)(4));
    }
    { Fl_Button* o = new Fl_Button(5, 145, 30, 25, gettext("MS"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(4);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_memory, (void*)(3));
    }
    { Fl_Button* o = new Fl_Button(50, 145, 30, 25, gettext("1"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(1));
    }
    { Fl_Button* o = new Fl_Button(85, 145, 30, 25, gettext("2"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(2));
    }
    { Fl_Button* o = new Fl_Button(120, 145, 30, 25, gettext("3"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(3));
    }
    { Fl_Button* o = new Fl_Button(155, 145, 30, 25, gettext("-"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(1);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_op, (void*)(5));
    }
    { Fl_Button* o = new Fl_Button(190, 145, 30, 25, gettext("1/x"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(1);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_op, (void*)(6));
    }
    { Fl_Button* o = new Fl_Button(5, 175, 30, 25, gettext("M+"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(4);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_memory, (void*)(4));
    }
    { Fl_Button* o = new Fl_Button(50, 175, 30, 25, gettext("0"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(3);
      o->callback((Fl_Callback*)cb_number, (void*)(0));
    }
    { Fl_Button* o = new Fl_Button(85, 175, 30, 25, gettext("+/-"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(2);
      o->callback((Fl_Callback*)cb_sign);
    }
    { Fl_Button* o = new Fl_Button(120, 175, 30, 25, gettext("."));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(2);
      o->callback((Fl_Callback*)cb_dot, (void*)(0));
    }
    { Fl_Button* o = new Fl_Button(155, 175, 30, 25, gettext("+"));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(1);
      o->labelcolor(3);
      o->callback((Fl_Callback*)cb_op, (void*)(7));
    }
    { Fl_Button* o = new Fl_Button(190, 175, 30, 25, gettext("="));
      o->box(FL_RSHADOW_BOX);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->color(2);
      o->labelcolor(0);
      o->callback((Fl_Callback*)cb_equal, (void*)(6));
    }
    { Fl_Box* o = mem_flag = new Fl_Box(5, 55, 30, 25, gettext("M"));
      o->box(FL_SHADOW_BOX);
    }
    { Fl_Button* o = display = new Fl_Button(5, 25, 215, 25, gettext("0."));
      o->box(FL_SHADOW_BOX);
      o->down_box(FL_DOWN_BOX);
      o->color(7);
      o->callback((Fl_Callback*)cb_display);
      o->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
      o->when(FL_WHEN_CHANGED);
    }
    o->end();
  }
  return w;
}
