// generated by Fast Light User Interface Designer (fluid) version 1.0102

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>

extern "C" {
extern void cb_group(Fl_Menu_*, void*);
extern void cb_clear(Fl_Button*, void*);
extern void cb_number(Fl_Button*, void*);
extern void cb_memory(Fl_Button*, void*);
extern void cb_sign(Fl_Button*, void*);
extern void cb_display(Fl_Button*, void*);
extern void cb_about(Fl_Widget*, void*);
extern void cb_copy(Fl_Widget*, void*);
extern void cb_paste(Fl_Widget*, void*);
extern void cb_op(Fl_Widget*, void*);
extern void cb_dot(Fl_Widget*, void*);
extern void cb_equal(Fl_Widget*, void*);

};

extern Fl_Box *mem_flag;
extern Fl_Button *display;
extern Fl_Menu_Item menu_[];
Fl_Window* make_window();
#endif
