
include ../Makedefs


#
# Documents to build...
#

DOCUMENTS	=


#
# Build everything...
#

all:	$(DOCUMENTS)


#
# Install everything...
#

install: $(DOCUMENTS)


#
# Clean output files...
#

clean:
	$(RM) $(DOCUMENTS)


