#
# "$Id: Makefile,v 1.2 2000/06/25 22:00:17 easysw Exp $"
#
# Documentation makefile for the Fast Light Environment (FLE).
#
# Copyright 1998-2000 by Bill Spitzak and others.
#
# This is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA.
#
# Please report all bugs and problems to "fltk-bugs@fltk.org".
#

include ../Makedefs


#
# Documents to build...
#

DOCUMENTS	=


#
# Build everything...
#

all:	$(DOCUMENTS)


#
# Install everything...
#

install: $(DOCUMENTS)


#
# Clean output files...
#

clean:
	$(RM) $(DOCUMENTS)


#
# End of "$Id: Makefile,v 1.2 2000/06/25 22:00:17 easysw Exp $".
#
